title: Kowndinya Boyalakuntla
name: Kowndinya Boyalakuntla
position: Ph.D. student in Computer Science
email: kb1204@scarletmail.rutgers.edu
description: Kowndinya Boyalakuntla is a Computer Science Ph.D. student at Rutgers University, advised
  by Prof. Abdeslam Boularias. Research in robot learning, planning, and manipulation.
baseurl: ''
url: https://kowndinya2000.github.io
twitter_username: KowndinyaB70872
github_username: kowndinya2000
linkedin_id: kowndinya-b-b4b254155
google_scholar: tv9b9Y4AAAAJ
timezone: America/New_York
markdown: kramdown
exclude:
- Gemfile
- Gemfile.lock
- README.md
- cv/build_cv.py
- cv/requirements.txt
- cv/Makefile
- cv/content.tex
- cv/kowndinya-cv.tex
- css
- js
- _sass
