title: Kowndinya Boyalakuntla
name: Kowndinya Boyalakuntla
position: Third-year Ph.D. student in Computer Science
email: kb1204@scarletmail.rutgers.edu
description: Kowndinya Boyalakuntla is a third-year Computer Science Ph.D. student at Rutgers University, advised
  by Prof. Abdeslam Boularias. Research in learning and planning for robot manipulation and whole-body
  control, learned world-models, and action abstractions from human motion capture for long-horizon
  humanoid loco-manipulation.
baseurl: ''
url: https://kowndinya2000.github.io
twitter_username: KowndinyaB70872
github_username: kowndinya2000
linkedin_id: kowndinya-b-b4b254155
google_scholar: tv9b9Y4AAAAJ
timezone: America/New_York
last_updated: Sep 2026
markdown: kramdown
exclude:
- Gemfile
- Gemfile.lock
- README.md
- cv/build_cv.py
- cv/requirements.txt
- cv/Makefile
- cv/content.tex
- cv/kowndinya-cv.tex
- css
- js
- _sass
